### ISSUE TITLE
Request to merge TSPLIB4J into OR project

### ISSUE THREAD

**Issue by jkinable** [dhadka/TSPLIB4J#1]
Dear David,

I've been working on several Operations Research (OR) projects. In an attempt to simplify and speed up the implementation of these projects, I'm currently bundling several well-known algorithms, frameworks etc into an open source Java library which is hosted on Github: https://github.com/jkinable/jorlib
Currently I'm working on the integration of a Column Generation framework into the project, but that's still part of the development branch. I'll incorporate it into the master branch somewhere next week.

To extend the code base, I was wondering whether you would allow me to include the TSPLib parser from TSPLIB4J into the project. This would be a great addition as TSP related problems occur very often in the area of OR. Would you be interested in contributing the code yourself? Alternatively, I can merge it myself?

Thank you for your effort!

Joris

**Comment by dhadka** [comment]
Joris,

I'm sorry for not responding sooner.  I never received an e-mail notification for this issue.  I'm more than happy for you to use the code (and am glad you've already merged the code without waiting for a response from me).

Best,
David
